version: "3.9"

services:
  frontend:
    image: nginx:stable-alpine
    container_name: "${COMPOSE_PROJECT_NAME}-frontend-server"
    #restart: unless-stopped
    ports:
      - "6100:80"
    volumes:
      - ./nginx/www:/var/www
      - ./nginx/config:/etc/nginx/conf.d
    networks:
      - nginx_network
    #command: nginx -g daemon off;

networks:
  nginx_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1